<?php

declare(strict_types=1);

/**
 * Contao Content Navigation
 *
 * @copyright 2010-2011 InfinitySoft
 * @copyright 2018 nickname. Büro für visuelle Kommunikation Nicky Hoff
 */

$GLOBALS['TL_LANG']['tl_content']['toc_legend'] = 'Table of contents';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_content']['hofff_toc_source']        = array('Artikel', 'Artikel auswählen, über den die Inhaltsnavigation erstellt werden soll.');
$GLOBALS['TL_LANG']['tl_content']['hofff_toc_min_level']     = array('Start Level', 'Bei dieser Überschriftenebene anfangen (inklusive).');
$GLOBALS['TL_LANG']['tl_content']['hofff_toc_max_level']     = array('Stopp Level', 'Bei dieser Überschriftenebene aufhören (inklusive).');
$GLOBALS['TL_LANG']['tl_content']['hofff_toc_include']       = array('Include in table of contents', 'Add element to table of content navigation if a headline is defined. Alias will be autogenerated if not set.');
$GLOBALS['TL_LANG']['tl_content']['hofff_toc_source_column'] = 'Artikel in Spalte';
$GLOBALS['TL_LANG']['tl_content']['hofff_toc_source_page']   = 'Artikel in Seite';
